modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="armorers_bane"
version="1.0.0"
displayName="Armorer's Bane"
credits="Made using MCreator."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="JMPotionwiz"
description="A small mod that debuffs constantly wearing armor"

[[dependencies.armorers_bane]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




