modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="armorers_bane"
version="1.0.0"
displayName="Armorer's Bane"
credits="Made using MCreator."
displayURL="https://modrinth.com/mod/armorers-bane"
logoFile="logo.png"
authors="JMPotionwiz"
description="A small mod that debuffs constantly wearing armor"

[[dependencies.armorers_bane]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




